# Generated by Django 4.2.2 on 2023-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0007_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='topic',
            field=models.CharField(max_length=300),
        ),
    ]
