# Generated by Django 4.2.2 on 2023-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0008_alter_newsmodel_content_alter_newsmodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='addamount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawamount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
