# Generated by Django 4.2.2 on 2023-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0011_wishlist_newsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
